name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build_and_push_docker_images:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    needs: build_with_maven

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push frontend Docker image
        if: github.event_name == 'workflow_run' && github.event.workflow == 'Java CI with Maven' && github.event.conclusion == 'success'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          cd frontend
          docker build -t boonchun/nus_team_9-frontend:latest . 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push boonchun/nus_team_9-frontend:latest  
          

      - name: Build and push backend Docker image
        if: github.event_name == 'workflow_run' && github.event.workflow == 'Java CI with Maven' && github.event.conclusion == 'success'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker build -t boonchun/nus_team_9-backend:latest . 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push boonchun/nus_team_9-backend:latest 
