name: CI/CD Pipeline

on:
  push:
    branches: [ "frontend" ]
  pull_request:
    branches: [ "frontend" ]

jobs:
  build_with_maven:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package

  build_and_push_docker_images:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    needs: build_with_maven
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Print current working directory
        run: echo "Current working directory is $(pwd)"

      - name: Build and push backend
        run: |
            docker build -t boonchun/nus_team_9:backend-latest . --build-arg JAR_FILE=target/nus-team-9.jar --no-cache          
            docker push boonchun/nus_team_9:backend-latest

      - name: Build and push frontend
        run: |
            cd frontend
            echo "Current working directory is $(pwd)"
            docker build -t boonchun/nus_team_9:frontend-latest . 
            docker push boonchun/nus_team_9:frontend-latest  


  deploy:
    name: Pull from Docker and Deploy
    needs: build_and_push_docker_images
    runs-on: [aws-ec2]
    steps:
      - name: Stop and remove old backend container
        run: |
          docker stop backend || true
          docker rm -f backend || true
      - name: Stop and remove old frontend container
        run: |
          docker stop frontend || true
          docker rm -f frontend || true
      - name: Pull image from Docker Hub for backend
        run: docker pull boonchun/nus_team_9:backend-latest
      - name: Pull image from Docker Hub for frontend
        run: docker pull boonchun/nus_team_9:frontend-latest
      - name: Run backend container
        run: docker run -d --name backend -p 8080:8080 boonchun/nus_team_9:backend-latest
      - name: Run frontend container
        run: docker run -d --name frontend -p 3000:3000 boonchun/nus_team_9:frontend-latest

