name: CI/CD Pipeline

on:
  push:
    branches: [ "frontend" ]
  pull_request:
    branches: [ "frontend" ]

jobs:
  build_with_maven:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean compile

  build_and_push_docker_images:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    needs: build_with_maven

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Dokcerhub
        if: github.event_name == 'workflow_run' && github.event.workflow == 'Java CI with Maven' && github.event.conclusion == 'success'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push backend
        run: |
          docker build -t boonchun/nus_team_9:backend-latest . 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push boonchun/nus_team_9:backend-latest 

      - name: Build and push frontend
        run: |
            cd frontend
            docker build -t boonchun/nus_team_9:frontend-latest . 
            docker push boonchun/nus_team_9:frontend-latest  



